### ISSUE TITLE
[Bug] namespace property misconfigured in application.yml

### ISSUE THREAD

**Issue by barrypower** [temporalio/spring-boot-demo#13]
### What are you really trying to do?

Configure temporal to use a namespace other than default.

### Describe the bug

After changing the namespace property in `application.yml` to a different value, workflows still appear under the default namespace.

### Minimal Reproduction

Starting with the demo app config:
```
  temporal:
    connection:
      target: 127.0.0.1:7233
      target.namespace: default
```

changed to:
```
  temporal:
    connection:
      target: 127.0.0.1:7233
      target.namespace: sbdemo
```

### Environment/Versions

n/a

### Additional context

The namespace property should be nested under temporal, e.g. 

```
  temporal:
    connection:
      target: 127.0.0.1:7233
    namespace: sbdemo
```
